name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - name: Publish
      run: dotnet publish ./MinecraftServerInfoPanel/MinecraftServerInfoPanel.csproj -c Release -o ./publish
    - name: Variable Substitution
      uses: microsoft/variable-substitution@v1 
      with:
        files: './publish/appsettings.json'
      env:
        Args.connectionString: "GHActions"
    - name: Create artifacts
      uses: actions/upload-artifact@v2
      with:
        path: ./publish/appsettings.json
